### ISSUE TITLE
Don't use whole play service for the sdk

### ISSUE THREAD

**Issue by modislaszlo** [adform/adform-tracking-android-sdk#1]
Using com.google.android.gms:play-service is wrong because ads a lot of not needed code and is increasing apk size. 
As far as I saw using com.google.android.gms:play-services-ads is enough. Please check if that is indeed enough and if yes update the documentation.

**Comment by sindrenm** [comment]
The documentation to date specifies only using the “ads” portion of the Play Services, so I suppose this can be closed?

From the README:
```
compile 'com.google.android.gms:play-services-ads:8.1.0'
```

(Even if the version number there is ages old. :stuck_out_tongue:)
