### ISSUE TITLE
Move to aar dependency instead of jar

### ISSUE THREAD

**Issue by gotev** [adform/adform-tracking-android-sdk#10]
On release `1.4.1` and previous versions, after adding AdForm tracking SDK to an Android project, a bunch of manual tasks have to be done on Application's manifest: https://github.com/adform/adform-tracking-android-sdk#3-update-androidmanifestxml

All those should be completely avoided, relying on [manifest merger](https://developer.android.com/studio/build/manifest-merge.html) capabilities. It's sufficient to add an AndroidManifest.xml to your library project and generate an `aar` instead of a `jar`. Currently all android libraries does this.

**Comment by svabas** [comment]
Issue has been addressed in the latest version
