### ISSUE TITLE
Fatal runtime-exception in Protobuf after updating to 2.4.0

### ISSUE THREAD

**Issue by cboisen** [adform/adform-tracking-android-sdk#16]
```
Fatal Exception: java.lang.RuntimeException
Field osVersion_ for d.a.b.a.a.b not found. Known fields are [private int d.a.b.a.a.b.e, private static final d.a.b.a.a.b d.a.b.a.a.b.f, private static volatile com.google.protobuf.y0 d.a.b.a.a.b.g]
```

in
`com.adform.adformtrackingsdk.web.ProtobufBuilder.buildAsProtoBuf (ProtobufBuilder.java:94)`

I'm downgrading back to a known working version for now. Just want to let you know it's broken.

**Comment by rprunskas** [comment]
It's obfuscation issue. Please add to your proguard/R8 rules:

```
-keep class com.adform.adformtrackingsdk.entities.** { *; }
-keep class com.adform.mobile.** { *; }
-dontwarn com.adform.adformtrackingsdk.entities.**
-dontwarn com.adform.mobile.**
```

**Comment by cboisen** [comment]
Thanks @rprunskas. Do you keep an "upgrade guide" somewhere that I can follow (in the future)?

**Comment by clhols** [comment]
@rprunskas You can add the proguard rules as a consumer proguard file then devs don't need to update their own proguard config. See:
https://android.jlelse.eu/proguard-r8-in-the-world-of-modularity-f599650b4553
