### ISSUE TITLE
Google Play Console Warning

### ISSUE THREAD

**Issue by bruzzers** [adform/adform-tracking-android-sdk#21]
Good morning,

I'm using this library in my project with 2.5.2 version and I notice that it's using com.google.android.gms:play-services-ads:19.1.0.

Google play console show me a warning about that, and suggest to use 19.2.0+ version for this lib.

Can you update your Lib or tell me suggestion to avoid this warning?

Thank you very much.

**Comment by rprunskas** [comment]
Hi, you could add com.google.android.gms:play-services-ads 19.2.0+ dependency in your build.gradle file by yourself now. We will release new tracking sdk as soon as possible. 

"Gradle resolves any dependency version conflicts by selecting the latest version found in the dependency graph."

**Comment by giovanniPolatoO** [comment]
Hi,
I have the same error and if I add the dependency "com.google.android.gms:play-services-ads 19.2.0" as suggested, cascading "Duplicate Class" errors are generated because conflicts with other libraries arise.

Can you please update the library?

**Comment by rolandasito** [comment]
We have change play-services-ads with play-services-ads-identifier you should no longer get a warning using 2.5.5 tracking sdk version.
