### ISSUE TITLE
First event not using HTTPS

### ISSUE THREAD

**Issue by cbaggers** [adform/adform-tracking-android-sdk#5]
The first event sent when calling `startTracking` is using http. I am basing this on the address in the log.

```
http://track.adform.net/mobile/trackpoint/?pm=1264576&ADFPageName=[__APPNAME__]%7CAndroid%7CStart&ADFdivider=|&md=ChBN[__REMOVED_290_CHARS__]cuMzYgKEtIVE1MLCBs%0AaWtlIEdlY2tvKSBWZXJzaW9uLzQuMCBDaHJvbWUvNjguMC4zNDQwLjkxIE1vYmlsZSBTYWZhcmkv%0ANTM3LjM2MgNIVENSAJIDMgoRQ1VTVE9NX0FQUF9FVkVOVFMSAmExEg9jb20uYXBwcy5zbHV0dGES%0AATASBTAuMC4w%0A
```

the sections between `[__` & `__]` have been remove in case of senstive information but otherwise this is unchanged.

Calling `AdformTrackingSdk.setHttpsEnabled(true);` before `startTracking` 'fixes' this issue but the documentation says that https is on by default so this is a bug.

**Comment by rprunskas** [comment]
Fixed in new release - https://github.com/adform/adform-tracking-android-sdk/commit/ab8c6b06c7466db7dc2c50de7be1d30737e96751

**Comment by cbaggers** [comment]
cheers!
