### ISSUE TITLE
Documentation shows setStep taking a string, however it takes a Byte

### ISSUE THREAD

**Issue by cbaggers** [adform/adform-tracking-android-sdk#6]
The documentation shows `setStep` being used like this:

```
productItem.setStep("Step");
```

However the method takes a `Byte`.

**Comment by rprunskas** [comment]
Fixed documentation - https://github.com/adform/adform-tracking-android-sdk/commit/5834d6beed3ec7c8429f18b953884ad987d30a55

**Comment by cbaggers** [comment]
thanks!
