### ISSUE TITLE
Protobuf Java vs. Protobuf JavaLite

### ISSUE THREAD

**Issue by jaroslavhavelik** [adform/adform-tracking-android-sdk#8]
Currently I'm tring to integrate your SDK to one of our clients apps, and we have issue that com.google.protobuf:protobuf-java is clashing with com.google.protobuf:protobuf-javalite. I'm getting following error when building the project:

> More than one file was found with OS independent path 'google/protobuf/type.proto'

I understand the issue, but i don't see any solution. However I have no previous experience with protobuf, so I would be glad for any suggestions.

It seems that lite version of protobuf is recommended solution for Android: [https://github.com/google/protobuf-gradle-plugin#default-outputs](https://github.com/google/protobuf-gradle-plugin#default-outputs). 

Any plans for migration to lite version of protobuf?
Or any suggestion how to have both javalite and java version in same project. It seems that lite version is used in Firebase Performance Monitoring?

**Comment by svabas** [comment]
Hi @jaroslavhavelik 
The requested change is available in the latest version
