### ISSUE TITLE
install_referrer intent broadcast deprecation

### ISSUE THREAD

**Issue by LukasVykuka** [adform/adform-tracking-android-sdk#9]
According to [this post](https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html) install_referrer intent broadcast will be deprecated. When do you replace it by suggested Play Install Referrer Library?

**Comment by svabas** [comment]
The fix is planned to be implemented by the end of the month (April 2020)

**Comment by LukasVykuka** [comment]
OK, thanks

**Comment by LukasVykuka** [comment]
What is status of this issue? I don't see any new release.

**Comment by svabas** [comment]
Issue has been fixed in version 2.0.2, released on April 30th, 2020
